import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: "#020b22",
    },
    container: {
        flex: 1,
        backgroundColor: "#020b22",
        paddingHorizontal: 16,
        paddingTop: 8,
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 14,
    },
    headerTitle: {
        color: "#fff",
        fontSize: 28,
        fontWeight: "800",
    },
    filterIconButton: {
        width: 46,
        height: 46,
        borderRadius: 14,
        backgroundColor: "#101932",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.08)",
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
    },
    redDot: {
        position: "absolute",
        top: 8,
        right: 8,
        width: 8,
        height: 8,
        borderRadius: 999,
        backgroundColor: "#ff4d67",
    },
    searchBox: {
        height: 56,
        borderRadius: 18,
        backgroundColor: "#0d1530",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.05)",
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 14,
        gap: 10,
        marginBottom: 8,
    },
    searchInput: {
        flex: 1,
        color: "#fff",
        fontSize: 15,
    },
    appliedFiltersWrap: {
        marginBottom: 8,
    },
    appliedFiltersRow: {
        gap: 10,
        paddingVertical: 6,
        paddingRight: 8,
    },
    appliedChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 16,
        backgroundColor: "#f3e2fb",
    },
    appliedChipText: {
        color: "#b04cff",
        fontSize: 14,
        fontWeight: "700",
    },
    listContent: {
        paddingTop: 4,
        paddingBottom: 28,
    },
    playerCard: {
        borderRadius: 22,
        backgroundColor: "#0b1431",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.04)",
        padding: 14,
        marginBottom: 12,
    },
    playerTop: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 10,
    },
    playerLeft: {
        flex: 1,
        flexDirection: "row",
        alignItems: "flex-start",
    },
    avatarCircle: {
        width: 54,
        height: 54,
        borderRadius: 27,
        backgroundColor: "#2f5cff",
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
    },
    avatarText: {
        color: "#fff",
        fontSize: 24,
        fontWeight: "800",
    },
    playerInfo: {
        flex: 1,
        minWidth: 0,
    },
    nameRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    playerName: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "800",
    },
    onlineDot: {
        width: 10,
        height: 10,
        borderRadius: 999,
        backgroundColor: "#2dd36f",
    },
    playerNick: {
        marginTop: 4,
        color: "#a7b3d5",
        fontSize: 14,
        fontWeight: "600",
    },
    playerMeta: {
        marginTop: 5,
        color: "#c0cae6",
        fontSize: 12,
    },
    playerBottom: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
        marginTop: 12,
    },
    smallChip: {
        paddingHorizontal: 10,
        paddingVertical: 7,
        borderRadius: 999,
        backgroundColor: "rgba(63,109,255,0.18)",
        borderWidth: 1,
        borderColor: "rgba(99,139,255,0.18)",
    },
    smallChipText: {
        color: "#8fb0ff",
        fontSize: 12,
        fontWeight: "700",
    },
    statusChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        paddingHorizontal: 10,
        paddingVertical: 7,
        borderRadius: 999,
        backgroundColor: "#0e1730",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.06)",
    },
    statusChipText: {
        color: "#dce4ff",
        fontSize: 12,
        fontWeight: "700",
    },
    profileButton: {
        height: 42,
        minWidth: 96,
        borderRadius: 14,
        backgroundColor: "#1c2748",
        borderWidth: 1,
        borderColor: "rgba(122,150,255,0.16)",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 14,
    },
    profileButtonText: {
        color: "#fff",
        fontSize: 13,
        fontWeight: "800",
    },
    emptyBox: {
        borderRadius: 22,
        backgroundColor: "#0b1431",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.04)",
        paddingVertical: 36,
        paddingHorizontal: 20,
        alignItems: "center",
        marginTop: 8,
    },
    emptyTitle: {
        marginTop: 10,
        color: "#fff",
        fontSize: 17,
        fontWeight: "800",
    },
    emptyText: {
        marginTop: 6,
        color: "#98a2c7",
        fontSize: 13,
        textAlign: "center",
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.45)",
        justifyContent: "flex-end",
    },
    modalSheet: {
        backgroundColor: "#fff",
        borderTopLeftRadius: 26,
        borderTopRightRadius: 26,
        paddingHorizontal: 18,
        paddingTop: 18,
        paddingBottom: 20,
        maxHeight: "85%",
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 14,
    },
    modalTitle: {
        fontSize: 28,
        fontWeight: "800",
        color: "#161616",
    },
    modalContent: {
        paddingBottom: 12,
        gap: 20,
    },
    filterBlock: {
        gap: 12,
    },
    filterBlockTitle: {
        fontSize: 22,
        fontWeight: "800",
        color: "#161616",
    },
    chipsWrap: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 10,
    },
    selectChip: {
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 15,
        backgroundColor: "#f2f2f6",
    },
    selectChipActive: {
        backgroundColor: "#f4e4fd",
    },
    selectChipText: {
        color: "#222",
        fontSize: 15,
        fontWeight: "600",
    },
    selectChipTextActive: {
        color: "#bb4dff",
        fontWeight: "700",
    },
    statusList: {
        gap: 10,
    },
    statusRow: {
        minHeight: 52,
        borderRadius: 16,
        backgroundColor: "#f5f5f7",
        paddingHorizontal: 14,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    statusRowActive: {
        backgroundColor: "#f3e4fd",
    },
    statusRowText: {
        flex: 1,
        color: "#222",
        fontSize: 15,
        fontWeight: "600",
    },
    statusRowTextActive: {
        color: "#b44fff",
        fontWeight: "700",
    },
    radioOuter: {
        width: 20,
        height: 20,
        borderRadius: 999,
        borderWidth: 2,
        borderColor: "#b7b7c9",
        alignItems: "center",
        justifyContent: "center",
    },
    radioOuterActive: {
        borderColor: "#b44fff",
    },
    radioInner: {
        width: 8,
        height: 8,
        borderRadius: 999,
        backgroundColor: "#b44fff",
    },
    modalButtons: {
        flexDirection: "row",
        gap: 12,
        marginTop: 10,
    },
    resetModalButton: {
        flex: 1,
        height: 54,
        borderRadius: 18,
        backgroundColor: "#efeff3",
        alignItems: "center",
        justifyContent: "center",
    },
    resetModalButtonText: {
        color: "#222",
        fontSize: 16,
        fontWeight: "700",
    },
    applyModalButton: {
        flex: 1,
        height: 54,
        borderRadius: 18,
        backgroundColor: "#b734ff",
        alignItems: "center",
        justifyContent: "center",
    },
    applyModalButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "800",
    },
});