import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: "#0b1220",
    },
    listContent: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 28,
    },
    headerBlock: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: 18,
    },
    brand: {
        color: "#60a5fa",
        fontSize: 14,
        fontWeight: "700",
        marginBottom: 6,
        letterSpacing: 0.3,
    },
    title: {
        color: "#f8fafc",
        fontSize: 28,
        fontWeight: "800",
    },
    subtitle: {
        color: "#94a3b8",
        fontSize: 14,
        marginTop: 8,
        lineHeight: 20,
        maxWidth: 250,
    },
    headerBadge: {
        backgroundColor: "#111827",
        borderWidth: 1,
        borderColor: "#1f2937",
        borderRadius: 14,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    headerBadgeText: {
        color: "#cbd5e1",
        fontSize: 12,
        fontWeight: "600",
    },
    searchBox: {
        backgroundColor: "#111827",
        borderColor: "#1f2937",
        borderWidth: 1,
        borderRadius: 18,
        paddingHorizontal: 14,
        height: 56,
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 14,
    },
    searchInput: {
        flex: 1,
        color: "#f8fafc",
        marginLeft: 10,
        fontSize: 15,
    },
    filterRow: {
        paddingBottom: 10,
        gap: 10,
    },
    filterChip: {
        backgroundColor: "#111827",
        borderWidth: 1,
        borderColor: "#1f2937",
        borderRadius: 999,
        paddingHorizontal: 16,
        paddingVertical: 10,
    },
    filterChipActive: {
        backgroundColor: "#60a5fa",
        borderColor: "#60a5fa",
    },
    filterChipText: {
        color: "#cbd5e1",
        fontWeight: "600",
        fontSize: 13,
    },
    filterChipTextActive: {
        color: "#08111f",
    },
    sectionRow: {
        marginTop: 8,
        marginBottom: 14,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    sectionTitle: {
        color: "#f8fafc",
        fontSize: 18,
        fontWeight: "700",
    },
    sectionLink: {
        color: "#60a5fa",
        fontSize: 13,
        fontWeight: "600",
    },
    card: {
        backgroundColor: "#111827",
        borderWidth: 1,
        borderColor: "#1f2937",
        borderRadius: 22,
        padding: 16,
        marginBottom: 14,
    },
    cardTop: {
        flexDirection: "row",
        alignItems: "center",
    },
    avatar: {
        width: 58,
        height: 58,
        borderRadius: 18,
        backgroundColor: "#1d4ed8",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 14,
    },
    avatarText: {
        color: "#eff6ff",
        fontSize: 24,
        fontWeight: "800",
    },
    cardInfo: {
        flex: 1,
    },
    nameRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    nickname: {
        color: "#f8fafc",
        fontSize: 18,
        fontWeight: "700",
    },
    statusDot: {
        width: 10,
        height: 10,
        borderRadius: 999,
    },
    statusOnline: {
        backgroundColor: "#22c55e",
    },
    statusOffline: {
        backgroundColor: "#64748b",
    },
    role: {
        color: "#93c5fd",
        fontSize: 14,
        marginTop: 4,
        fontWeight: "600",
    },
    city: {
        color: "#94a3b8",
        fontSize: 13,
        marginTop: 4,
    },
    modeBadge: {
        backgroundColor: "#0b1220",
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: "#223049",
        marginLeft: 10,
    },
    modeBadgeText: {
        color: "#cbd5e1",
        fontSize: 12,
        fontWeight: "700",
    },
    cardBottom: {
        marginTop: 16,
        borderTopWidth: 1,
        borderTopColor: "#1f2937",
        paddingTop: 14,
    },
    onlineBox: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 14,
        gap: 6,
    },
    onlineText: {
        color: "#94a3b8",
        fontSize: 13,
        fontWeight: "500",
    },
    actionRow: {
        flexDirection: "row",
        gap: 10,
    },
    secondaryButton: {
        flex: 1,
        height: 44,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: "#334155",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#0b1220",
    },
    secondaryButtonText: {
        color: "#e2e8f0",
        fontSize: 14,
        fontWeight: "700",
    },
    primaryButton: {
        flex: 1,
        height: 44,
        borderRadius: 14,
        backgroundColor: "#60a5fa",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
        gap: 8,
    },
    primaryButtonText: {
        color: "#08111f",
        fontSize: 14,
        fontWeight: "800",
    },
    emptyState: {
        marginTop: 40,
        alignItems: "center",
        justifyContent: "center",
        padding: 24,
    },
    emptyTitle: {
        color: "#f8fafc",
        fontSize: 18,
        fontWeight: "700",
        marginTop: 12,
    },
    emptySubtitle: {
        color: "#94a3b8",
        fontSize: 14,
        marginTop: 8,
        textAlign: "center",
    },
});